version: "3"
services:
  frontend:
    build: ./frontend
    image: avttcs/movie-frontend:latest
    ports:
      - 3000:80
    networks:
      - movie-network
  backend:
    build: ./backend
    image: avttcs/movie-backend:latest
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - DB_CONNECTION=mongodb://mongodb:27017/test
    ports:
      - 5000:5000
    networks:
      - movie-network
  mongodb:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - movie-network
networks:
  movie-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local